### ISSUE TITLE
How do I get rid of those lines?

### ISSUE THREAD

**Issue by gino** [lucien144/cobalt2-phpstorm#1]
How do I get rid of those lines?

http://i.imgur.com/m9d3mos.png

**Comment by lucien144** [comment]
Hi @Gino. 
The right line is called `Right margin` and can be turned off in `Editor > General > Appearance > Show right margin`

The horizontal line is called `Method separator` in `Editor > Colors & Fonts > General > Code > Method separator color`

I'll consider implementing this in the theme.
